// <auto-generated>
using System.Threading.Tasks;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Synergy.VirusPrototype.Shared.Scenes.Abstract;

namespace Synergy.VirusPrototype.Shared.Scenes.Menu
{
	public class MenuScene : IMenuScene
	{
		private readonly SpriteFont _font;
		private readonly SpriteBatch _spriteBatch;

		public MenuScene(
			SpriteBatch spriteBatch,
			ContentManager contentManager)
		{
			_spriteBatch = spriteBatch;
			_font = contentManager.Load<SpriteFont>("Fonts\\Sprocket");
		}

		public Task NavigateAsync()
		{
			_spriteBatch.Begin();

			_spriteBatch.DrawString(_font, "Test Field", new Vector2(0, 0), Color.Black, 0, new Vector2(0, 0), 1f, SpriteEffects.None, 0);

			_spriteBatch.End();

			return Task.CompletedTask;
		}
	}
}
