// <auto-generated>
using System.Threading.Tasks;
using MediatR;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Synergy.VirusPrototype.Shared.Navigation.Abstract;

namespace Synergy.VirusPrototype.Shared.Navigation
{
	public class SceneNavigator : ISceneNavigator
	{
		private readonly SpriteBatch _spriteBatch;
		private readonly SpriteFont _font;

		public SceneNavigator(
			SpriteBatch spriteBatch,
			IMediator mediator,
			ContentManager contentManager)
		{
			_spriteBatch = spriteBatch;
			_font = contentManager.Load<SpriteFont>("Fonts/gameFont");
		}

		public Task StartAsync()
		{
			_spriteBatch.Begin();

			_spriteBatch.DrawString(_font, "Test Field", new Vector2(0, 0), Color.Black, 0, new Vector2(0, 0), 1f, SpriteEffects.None, 0);

			_spriteBatch.End();

			return Task.CompletedTask;
		}
	}
}
