// <auto-generated>
using System.Linq;
using Android.App;
using Android.Content.PM;
using Android.OS;
using Android.Views;
using Microsoft.Xna.Framework;
using Synergy.VirusPrototype.Shared;

namespace Synergy.VirusPrototype.Android
{
	[Activity(
		Label = "@string/app_name",
		MainLauncher = true,
		Icon = "@drawable/icon",
		AlwaysRetainTaskState = true,
		LaunchMode = LaunchMode.SingleInstance,
		ScreenOrientation = ScreenOrientation.FullUser,
		ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.Keyboard | ConfigChanges.KeyboardHidden | ConfigChanges.ScreenSize
	)]
	public class MainActivity : AndroidGameActivity
	{
		//	protected override void OnCreate(Bundle bundle)
		//	{
		//		base.OnCreate(bundle);

		//		GameStartup game = new GameStartup();
		//		View view = game.Services.GetService(typeof(View)) as View;

		//		SetContentView(view);
		//		game.Run();
		//	}
		//}

		protected override async void OnCreate(Bundle bundle)
		{
			base.OnCreate(bundle);

			await SharedProgram.Main(new string[] { });
			
			View view = SharedProgram.Game.Services.GetService(typeof(View)) as View;

			SetContentView(view);
		}
	}
}
