// <auto-generated>
using System.Collections.Generic;
using Microsoft.Xna.Framework.Graphics;
using Synergy.VirusPrototype.Core.Controls.Abstract;
using Synergy.VirusPrototype.Shared.Services.Abstract;

namespace Synergy.VirusPrototype.Core.Controls
{
	public class Grid : IView, ITexture
	{
		private readonly IRectangleDrawer _rectangleDrawer;
		private readonly GraphicsDevice _graphicsDevice;

		public Grid(
			IRectangleDrawer rectangleDrawer,
			GraphicsDevice graphicsDevice)
		{
			Rows = new List<RowDefinition>();
			
			Width = graphicsDevice.Viewport.Bounds.Width;
			Height = graphicsDevice.Viewport.Bounds.Height;
			_rectangleDrawer = rectangleDrawer;
			_graphicsDevice = graphicsDevice;
		}

		public int Width { get; set; }

		public int Height { get; set; }

		public IView? Parent { get; set; }

		public ICollection<RowDefinition> Rows { get; set; }

		public Texture2D Texture { get; set; }
	}
}
