// <auto-generated>
namespace Synergy.VirusPrototype.Core.Controls
{
	public struct GridLength
	{
		public GridLength(double value, GridUnitType type)
		{
			Value = value;
			UnitType = type;
		}

		public GridUnitType UnitType { get; set; }

		public double Value { get; set; }
	}
}
