name: .NET Core

on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

env:
  CrossPlatformProject: 'src/platforms/Synergy.VirusPrototype.CrossPlatformDesktop/Synergy.VirusPrototype.CrossPlatformDesktop.csproj'
  SharedUnitTestProject: 'test/Synergy.VirusPrototype.Shared.Tests.Unit/Synergy.VirusPrototype.Shared.Tests.Unit.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{env.CrossPlatformProject}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.SharedUnitTestProject}} --no-restore --verbosity normal
